### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by zuurw** [lennart-k/HomeControl#2]
Hi, how are you? I'd like to collaborate on your open source project and propose free logo/icon design for this project. If it's something you're interested in, please, let me know!
Best Regards
Zuur

**Comment by lennart-k** [comment]
Hi,
I think that would be quite amazing. :smiley: 
If you have some spare time I would be really happy about a logo.

**Comment by zuurw** [comment]
Hi, I would like to know what do you want for this logo, can you give me something to get inspired?

Thank you!

Best Regards!

**Comment by lennart-k** [comment]
I think a very abstract logo would be quite nice, that also works well when scaled far down for example as a tab icon in the web browser.

I feel like a house would be obvious, but maybe a little control panel inside or some radio waves could look neat.

As a little example for a style I could imagine I made this, which honestly looks a little crappy but maybe it's enough to show what I mean.
![Screenshot from 2019-05-30 14-16-53](https://user-images.githubusercontent.com/18233294/58632556-2799f180-82e6-11e9-8fd8-4d07b2752e47.png)

**Comment by zuurw** [comment]
Thanks, I will try to design something good!!!

**Comment by zuurw** [comment]
Hi, how are you? See if you like one of this logo that I design for this project.

Greetings!!!

![HOME CONTROL](https://user-images.githubusercontent.com/40801473/58874189-01969780-86c0-11e9-9801-ab78afebd943.jpg)

**Comment by lennart-k** [comment]
Hi,
thank you for the designs :D
I think the best logos are the red and the beige logo.
I feel like the beige one with a lower radius for the waves and a little bolder strokes would be perfect.

**Comment by zuurw** [comment]
Here are some variations, see if you like one of this.

Greetings!

![HOME CONTROL2](https://user-images.githubusercontent.com/40801473/58891545-9b703b80-86e4-11e9-93ed-a6f88da07d3e.jpg)

**Comment by lennart-k** [comment]
Hi, thanks for the variations.
I think the best would be just the first one (not the 1) with just a tiny bit bolder strokes.
I feel like the stroke width from variation 1 would be perfect

**Comment by zuurw** [comment]
It´s this what you want?

![HOME CONTROL3](https://user-images.githubusercontent.com/40801473/59028369-6504fe80-8853-11e9-9fd7-5d55fee7896c.jpg)

**Comment by lennart-k** [comment]
Hmm, sorry for being so picky D:
I've changed my mind a bit and I think the version you showed before is really good as a final version.
Thank you for your effort and patience. :slightly_smiling_face: 
![Screenshot from 2019-06-06 14-06-02](https://user-images.githubusercontent.com/18233294/59031539-422f1600-8864-11e9-999c-2c593ababf82.png)

**Comment by zuurw** [comment]
No problem, I will create the files of the logo, also in black and white version and I will send it to you.

Greetings!

**Comment by zuurw** [comment]
Hi @lennart-k 
I apologize for the late reply. I submitted all the logo files hope everything is ok. Greetings.

**Comment by lennart-k** [comment]
Thank you, I will close this issue now :D
